competition_blogcomment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: CompetitionBlogBundle:BlogComment:create }
    requirements:
        _method:  POST
        blog_id: \d+


competition_blog_show:
    pattern:  /blog/{id}/{slug}
    defaults: { _controller: CompetitionBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
