competition_blog_show:
    pattern:  /{id}
    defaults: { _controller: CompetitionBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

competition_blogcomment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: CompetitionBlogBundle:BlogComment:create }
    requirements:
        _method:  POST
        blog_id: \d+
