competition_blogcomment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: CompetitionBlogBundle:BlogComment:create }
    requirements:
        _method:  POST
        blog_id: \d+


competition_blog_show:
    pattern:  /{_locale}/blog/{id}/{slug}
    defaults: { _controller: CompetitionBlogBundle:Blog:show, _locale: es }
    requirements:
        _method:  GET
        id: \d+
        _locale: es|en
