parameters:
#    competition_blog.example.class: Competition\BlogBundle\Example

services:
#    competition_blog.example:
#        class: %competition_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
