competition_frontend_homepage:
    pattern:  /
    defaults: { _controller: CompetitionFrontendBundle:Page:index }

competition_frontend_about:
    pattern:  /about
    defaults: { _controller: CompetitionFrontendBundle:Page:about }
