competition_frontend_homepage:
    pattern:  /{_locale}/{game_id}
    defaults: { _controller: CompetitionFrontendBundle:Page:index, _locale: es, game_id: 0}
    requirements:
        _locale: es|en

competition_frontend_about:
    pattern:  /{_locale}/about
    defaults: { _controller: CompetitionFrontendBundle:Page:about }
    requirements:
            _locale: es|en

