competition_game_select_redirect:
    pattern:  /{_locale}/selectgame
    defaults: { _controller: CompetitionGameBundle:Game:redirect }
    requirements:
        _method:  POST
        _locale: es|en
