parameters:
#    competition_match.example.class: Competition\MatchBundle\Example

services:
#    competition_match.example:
#        class: %competition_match.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
