competition_team_create:
    pattern:  /team/create
    defaults: { _controller: CompetitionTeamBundle:Team:create }
    requirements:
        _method:  POST
competition_team_show:
    pattern:  /{_locale}/team/{id}/
    defaults: { _controller: CompetitionTeamBundle:Team:show, _locale: es }
    requirements:
        _method:  GET
        id: \d+
        _locale: es|en
competition_team_new:
    pattern:  /team/new
    defaults: { _controller: CompetitionTeamBundle:Team:new }
    requirements:
        _method:  GET
