competition_team_create:
    pattern:  /{_locale}/team/create
    defaults: { _controller: CompetitionTeamBundle:Team:create }
    requirements:
        _method:  GET|POST
        _locale: es|en
competition_team_show:
    pattern:  /{_locale}/team/{id}/
    defaults: { _controller: CompetitionTeamBundle:Team:show, _locale: es }
    requirements:
        _method:  GET
        id: \d+
        _locale: es|en
