parameters:
#    competition_team.example.class: Competition\TeamBundle\Example

services:
    competition_team.team.type:
        class: Competition\TeamBundle\Form\TeamType
        arguments:
        tags:
            - { name: form.type, alias: competition_teambundle_teamtype }
