services:
    sonata.admin.user:
        class: Competition\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: users, label: "Users" }
        arguments:
            - ~
            - Competition\UserBundle\Entity\User
            - 'SonataAdminBundle:CRUD'