parameters:
#    competition_user.example.class: Competition\UserBundle\Example

services:
#    competition_user.example:
#        class: %competition_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
