parameters:
#    competition_user.example.class: Competition\UserBundle\Example

services:
    competition_user.registration.form.type:
        class: Competition\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: competition_user_registration }
